#%RAML 1.0
title: Faretrotter Travel API
description: Multimodal travel API to return modes of transportation between cities and points of interest.
version: '2.0'
protocols:
  - HTTPS
baseUri: 'https://api.faretrotter.com/v2.0/{apikey}'
securitySchemes:
  ApiKeyAuth:
    type: Pass Through
    describedBy:
      headers:
        ApiKeyAuth:
          type: string
annotationTypes:
  oas-schema-title:
    type: string
    allowedTargets: TypeDeclaration
  oas-summary:
    type: string
    allowedTargets: Method
types:
  PlaceResponse:
    properties:
      id:
        type: string
      name:
        type: string
      name_long:
        type: string
      city:
        type: string
      region:
        type: string
      country:
        type: string
      type:
        type: string
      slug:
        type: string
      lat:
        type: number
      lng:
        type: number
      geoname_id:
        type: string
    (oas-schema-title): Place response
  PlacesResponse:
    properties:
      status:
        type: object
        properties:
          code:
            type: number
          message:
            type: string
      request:
        type: object
        properties:
          environment:
            type: string
          version:
            type: string
          endpoint:
            type: string
          fields:
            type: object
            properties:
              origin_lat:
                type: number
              origin_lng:
                type: number
              destination_lat:
                type: number
              destination_lng:
                type: number
          distance_miles:
            type: number
      places:
        type: array
        items:
          type: PlaceResponse
    (oas-schema-title): Places response
  RoutesResponse:
    properties:
      status:
        type: object
        properties:
          code:
            type: number
          message:
            type: string
      request:
        type: object
        properties:
          environment:
            type: string
          version:
            type: string
          endpoint:
            type: string
          fields:
            type: object
            properties:
              origin_lat:
                type: number
              origin_lng:
                type: number
              destination_lat:
                type: number
              destination_lng:
                type: number
          distance_miles:
            type: number
      data:
        properties:
          routes:
            type: array
            items:
              type: object
              properties:
                origin_id:
                  type: string
                destination_id:
                  type: string
                mode:
                  type: string
                fare:
                  type: number
                duration:
                  type: number
                co2:
                  type: number
          places:
            type: array
            items:
              type: PlaceResponse
          operators:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                logo_img:
                  type: string
                mode:
                  type: string
                code:
                  type: string
                attributes:
                  type: array
                  items:
                    type: string
      response:
        type: object
        properties:
          url:
            type: string
          time:
            type: number
    (oas-schema-title): Routes response
/places:
  get:
    displayName: GET_places
    responses:
      '200':
        description: Everything worked as expected.
        body:
          application/json:
            type: PlaceResponse
      '400':
        description: Parameters did not match the endpoint requirements. Check that all required fields are present and spelt correctly.
      '401':
        description: Authentication Failed.
      '402':
        description: All parameters are correct but the request failed.
      '403':
        description: Request IP does not match IP address registered with key.
      '404':
        description: The endpoint doesn't exist.
      '429':
        description: Too many requests hit the API too quickly.
      '501':
        description: Server error
      '502':
        description: Server error
    (oas-summary): Returns possible modes of transportation between two cities.
/routes:
  get:
    responses:
      '200':
        description: Everything worked as expected.
        body:
          application/json:
            type: RoutesResponse
      '400':
        description: Parameters did not match the endpoint requirements. Check that all required fields are present and spelt correctly.
      '401':
        description: Authentication Failed.
      '402':
        description: All parameters are correct but the request failed.
      '403':
        description: Request IP does not match IP address registered with key.
      '404':
        description: The endpoint doesn't exist.
      '429':
        description: Too many requests hit the API too quickly.
      '501':
        description: Server error
      '502':
        description: Server error
    queryParameters:
      origin_lat:
        type: number
      origin_lng:
        type: number
      destination_lat:
        type: number
      destination_lng:
        type: number
